### PR TITLE
Add deepsearch test branch

### PR DESCRIPTION
**Pull request by cryck**
by @seambr

Added to extra branch so it triggers the preview. Noticed that the tokenization file is too big. Will check what options we have.

### CODE REVIEW

**Comment by cryck** [comment]
@seambr do you know what is causing the `script.js:117 Error fetching data: TypeError: results.forEach is not a function` on the test branch?

**Comment by seambr** [comment]
> @seambr do you know what is causing the `script.js:117 Error fetching data: TypeError: results.forEach is not a function` on the test branch?

im not sure, im not getting that when i run it locally.

**Comment by seambr** [comment]
https://polished-bush-fd60.cryck.workers.dev/?input=apple&isBackwards=false

https://polished-bush-fd60.cryck.workers.dev/?input=apple&isBackwards=false&isDepth=false

Both are making request to the same endpoint so the new test branch is expecting an extra layer but its receiving the same data as the main branch

**Comment by cryck** [comment]
Ohhh I know why. Thats on me. Let me fix that.

**Comment by cryck** [comment]
@seambr Brilliant work for real! Love the deep search. Possibly need to instruct the user a little better on what Total, Start & End mean with some tooltips or improved naming, but that can come in the future. 

Thank you so much for the contribution 🙏

**Review by seambr — APPROVED** [review]

**Pull request merged**
